bnxt: Add support for udp_tunnel_port_add/del dev_ops
Broadcom/dpdk pull request #17
Opened 2017-02-01 00:17 UTC by ajitkhaparde

Add support for udp_tunnel_port_add/del dev_ops to configure a UDP port
for VXLAN and Geneve Tunnel protocols.

Signed-off-by: Ajit Khaparde <ajit.khaparde@broadcom.com>

2017-02-01 08:10 UTC, stephen-hurd approved these changes
Approved, though we need to have a conversation about constant sizes.

2017-02-01 08:10 UTC, stephen-hurd commented on drivers/net/bnxt/hsi_struct_def_dpdk.h
> +	#define TUNNEL_DST_PORT_ALLOC_REQ_TUNNEL_TYPE_VXLAN       UINT32_C(0x1)
This field is only 8-bits wide... this sohuld likely be UINT8_C()  Same problem in other places, I suppose it's fine for now but we need to look at this through the while header.

2017-02-01 08:15 UTC, stephen-hurd requested changes
What is the count for if we only have one?

2017-02-01 08:15 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +		bp->vxlan_fw_dst_port_id = resp->tunnel_dst_port_id;
This overwrites the port ID, but maintains a count.  This looks like a resource leak.

2017-02-01 15:57 UTC, ajitkhaparde commented on drivers/net/bnxt/bnxt_hwrm.c
> +		bp->vxlan_fw_dst_port_id = resp->tunnel_dst_port_id;
Right. We support only one port. Will add code to prevent the over-write.

2017-02-01 16:37 UTC, ajitkhaparde commented
Can you check if the new logic handles the case that you pointed out. Thanks

2017-02-01 20:36 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +		bp->vxlan_fw_dst_port_id = resp->tunnel_dst_port_id;
This still allows one of each... do we support that?

2017-02-01 22:21 UTC, ajitkhaparde commented
How does this look now?

2017-02-02 00:03 UTC, stephen-hurd approved these changes

2017-02-02 00:04 UTC, merged