bnxt: Add support for rte_pmd_bnxt_set_vf_mac_anti_spoof
Broadcom/dpdk pull request #23
Opened 2017-02-03 17:44 UTC by ajitkhaparde

Add support for rte_pmd_bnxt_set_vf_mac_anti_spoof to enable VF MAC anti spoof.

Signed-off-by: Ajit Khaparde <ajit.khaparde@broadcom.com>

2017-02-06 22:09 UTC, stephen-hurd requested changes
More generic flag setting is possible.

2017-02-06 22:09 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +int bnxt_hwrm_func_cfg_set_vf_mac_spoof(struct bnxt *bp, uint16_t vf,
This should just be something like bnxt_hwrm_func_cfg_set_flags() and not take a flags argument.

2017-02-06 22:09 UTC, stephen-hurd commented on drivers/net/bnxt/rte_pmd_bnxt.c
> +	rc = bnxt_hwrm_func_cfg_set_vf_mac_spoof(bp, vf, func_flags);
This should just set the flags directly, then call the set flags function.  Unfortunately, the return code can be in response to any of the flag bits, not just the one we're changing.

2017-02-06 22:15 UTC, ajitkhaparde commented
On Mon, Feb 6, 2017 at 4:09 PM, Stephen Hurd <notifications@github.com>
wrote:

> *@stephen-hurd* requested changes on this pull request.
>
> More generic flag setting is possible.
> ------------------------------
>
> In drivers/net/bnxt/bnxt_hwrm.c
> <https://github.com/Broadcom/dpdk/pull/23#pullrequestreview-20381988>:
>
> > @@ -2113,3 +2113,19 @@ int bnxt_hwrm_func_bw_cfg(struct bnxt *bp, uint16_t vf,
>
>  	return rc;
>  }
> +
> +int bnxt_hwrm_func_cfg_set_vf_mac_spoof(struct bnxt *bp, uint16_t vf,
>
> This should just be something like bnxt_hwrm_func_cfg_set_flags() and not
> take a flags argument.
> ------------------------------
>
> In drivers/net/bnxt/rte_pmd_bnxt.c
> <https://github.com/Broadcom/dpdk/pull/23#pullrequestreview-20381988>:
>
> > +
> +	if (on > 1)	
> +		return -EINVAL;
> +
> +	/* Prev setting same as new setting. */
> +	if (on == bp->pf.vf_info[vf].mac_spoof_en)
> +		return 0;
> +
> +	func_flags = bp->pf.vf_info[vf].func_cfg_flags;
> +
> +	if (on)
> +		func_flags |= HWRM_FUNC_CFG_INPUT_FLAGS_SRC_MAC_ADDR_CHECK;
> +	else
> +		func_flags &= ~HWRM_FUNC_CFG_INPUT_FLAGS_SRC_MAC_ADDR_CHECK;
> +
> +	rc = bnxt_hwrm_func_cfg_set_vf_mac_spoof(bp, vf, func_flags);
>
> This should just set the flags directly, then call the set flags function.
> Unfortunately, the return code can be in response to any of the flag bits,
> not just the one we're changing.
>
​Hmm.. I thought only the "new" flag would be responsible for the return
code.
So if the return status is not necessarily because of the new flag, then I
will modify it to avoid the flags argument and just set the flags directly
before calling the hwrm function.

New patch-set coming up.​

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Broadcom/dpdk/pull/23#pullrequestreview-20381988>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AXqwrIZNZE7JNzWNSXzKQFuExB0Sd9zSks5rZ5oCgaJpZM4L2m8E>
> .
>

2017-02-07 03:07 UTC, stephen-hurd approved these changes

2017-02-07 03:07 UTC, stephen-hurd commented on drivers/net/bnxt/rte_pmd_bnxt.c
> +			bp->pf.vf_info[vf].mac_spoof_en = 0;
Why not just bp->pf.vf_info[vf].mac_spoof_en = on;

2017-02-07 03:18 UTC, ajitkhaparde commented
:-) yes. why not. Will fix up that.

On Mon, Feb 6, 2017 at 9:07 PM, Stephen Hurd <notifications@github.com>
wrote:

> *@stephen-hurd* approved this pull request.
> ------------------------------
>
> In drivers/net/bnxt/rte_pmd_bnxt.c
> <https://github.com/Broadcom/dpdk/pull/23#pullrequestreview-20421871>:
>
> > +
> +	func_flags = bp->pf.vf_info[vf].func_cfg_flags;
> +
> +	if (on)
> +		func_flags |= HWRM_FUNC_CFG_INPUT_FLAGS_SRC_MAC_ADDR_CHECK;
> +	else
> +		func_flags &= ~HWRM_FUNC_CFG_INPUT_FLAGS_SRC_MAC_ADDR_CHECK;
> +
> +	bp->pf.vf_info[vf].func_cfg_flags = func_flags;
> +
> +	rc = bnxt_hwrm_func_cfg_vf_set_flags(bp, vf);
> +	if (!rc) {
> +		if (on)
> +			bp->pf.vf_info[vf].mac_spoof_en = 1;
> +		else
> +			bp->pf.vf_info[vf].mac_spoof_en = 0;
>
> Why not just bp->pf.vf_info[vf].mac_spoof_en = on;
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Broadcom/dpdk/pull/23#pullrequestreview-20421871>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AXqwrMUlOGWl2TaxTGV46vGzYb0YTWcUks5rZ-AKgaJpZM4L2m8E>
> .
>

2017-02-07 03:28 UTC, merged