Add function rte_pmd_bnxt_set_tx_loopback and rte_pmd_bnxt_set_all_queues_drop_en
Broadcom/dpdk pull request #5
Opened 2017-01-20 04:47 UTC by steevenlee

2017-01-20 04:50 UTC, steevenlee commented on drivers/net/bnxt/bnxt_ethdev.c
> +int rte_pmd_bnxt_set_tx_loopback(uint8_t port, uint8_t on)
This method invoked by VFd, not supported by HWRM now, not sure whether we should keep the stub.

2017-01-20 05:01 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +			resp->flags) & HWRM_VNIC_QCFG_OUTPUT_FLAGS_BD_STALL_MODE;
although bd_stall can be set here and read out correctly later, traffic still pass despite of bd_stall flag, not sure how to debug chimp under dpdk or how to involve chimp team on this...

2017-01-20 05:02 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +		if (rc)
It looks that bd_stall flag can be retrieved correctly here.

2017-01-20 19:01 UTC, ajitkhaparde commented on drivers/net/bnxt/bnxt_ethdev.c
> +int rte_pmd_bnxt_set_tx_loopback(uint8_t port, uint8_t on)
I suggest moving all these rte_pmd_bnxt_xyz() implementions into its own rte_pmd_bnxt.c 
Are you talking of supporting in bnxt_hwrm.c or HWRM API?
I think HWRM API already allows toggling NO-VEB, VEB, VEPA anyway.
hwrm_func_cfg

Am I missing something?

2017-01-20 22:15 UTC, stephen-hurd requested changes
Looks good for the most part.  I do like the additional vnic fields.

2017-01-20 22:15 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_ethdev.c
> +		rc = bnxt_hwrm_func_vf_stall(bp, i, on);
This bit may actually mean the opposite of what on means.  We should check with Hemal about this.

2017-01-20 22:15 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_hwrm.c
> +			resp->flags) & HWRM_VNIC_QCFG_OUTPUT_FLAGS_BD_STALL_MODE;
The only time traffic should stall is when a ring is full and the hardware mbufs are also full.  You would need to create a test that sets the stall bit then doesn't service the RX ring.  When that happens, other RX rings would stop receiving traffic.

2017-01-20 22:15 UTC, stephen-hurd commented on drivers/net/bnxt/hsi_struct_def_dpdk.h
> +    #define HWRM_VNIC_QCFG_INPUT_ENABLES_VF_ID_VALID           0x1UL
This should be switched to (UINT32_C(0x1)) to be the same as other constants and the correct size.

2017-01-20 22:15 UTC, stephen-hurd commented on drivers/net/bnxt/hsi_struct_def_dpdk.h
> +    #define HWRM_VNIC_QCFG_OUTPUT_FLAGS_RSS_DFLT_CR_MODE       0x20UL
These constants should use UINT32_C() as well.

2017-01-21 00:08 UTC, ajitkhaparde commented on drivers/net/bnxt/hsi_struct_def_dpdk.h
> +    #define HWRM_VNIC_QCFG_INPUT_ENABLES_VF_ID_VALID           0x1UL
Let me send you the file which is adapted to the dpdk submission process.

2017-01-21 00:10 UTC, ajitkhaparde reviewed
Stephen has requested changes anyway. Not doubling on that again.

2017-01-22 03:07 UTC, steevenlee commented on drivers/net/bnxt/bnxt_ethdev.c
> +int rte_pmd_bnxt_set_tx_loopback(uint8_t port, uint8_t on)
From hwrm source, it looks that HWRM API just defined it and not getting it implemented yet.

2017-01-22 05:27 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +			resp->flags) & HWRM_VNIC_QCFG_OUTPUT_FLAGS_BD_STALL_MODE;
This works for PF by clearing not servicing BOTH dflt_ring_group and enable bit.
But for VF, dflt_ring_group will lost after setting 0.

2017-01-22 06:59 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +			resp->flags) & HWRM_VNIC_QCFG_OUTPUT_FLAGS_BD_STALL_MODE;
To make things simple, how about requesting hwrm change by adding "enable" flag option to switch bd_stall only.

2017-01-24 06:05 UTC, steevenlee commented on drivers/net/bnxt/hsi_struct_def_dpdk.h
> +    #define HWRM_VNIC_QCFG_INPUT_ENABLES_VF_ID_VALID           0x1UL
Ajit, that's great to know how to generate the file.

2017-01-24 10:52 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +			resp->flags) & HWRM_VNIC_QCFG_OUTPUT_FLAGS_BD_STALL_MODE;
Got a workaround on this, see latest commit

2017-01-24 10:54 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +	}
This works well for both PF and VF now

2017-01-24 10:58 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +	req.evb_mode = bp->pf.evb_mode;
I can see VEB mode works, while VEPA does not...

2017-01-24 11:00 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +	bp->pf.evb_mode = resp->evb_mode;
Always return 0, although it looks that NIC is forwarding as VEB mode.

2017-01-24 11:03 UTC, steevenlee commented on drivers/net/bnxt/bnxt_hwrm.c
> +			vnic.dflt_ring_grp = bp->pf.vnic_dflt_ring_group[vnic.fw_vnic_id];
Has to set dflt_ring_group to 0 to make bd_stall work, next qcfg will return 0, has to cache here.

2017-01-24 11:07 UTC, steevenlee commented on drivers/net/bnxt/bnxt.h
> +	uint16_t 		vnic_dflt_ring_group[340];
It looks that ring group range from 170 to 340, not sure how to calculate the start and stop.

2017-01-25 03:19 UTC, stephen-hurd approved these changes

2017-01-25 04:46 UTC, merged