Support setting VF mac address
Broadcom/dpdk pull request #8
Opened 2017-01-25 11:09 UTC by steevenlee

This set mac feature works only work when VF not started, in other words, to setup VF mac, has to stop testpmd that binds to VF. Configure on-the-fly wouldn't work, is this the expected model?

2017-01-25 20:54 UTC, ajitkhaparde commented
I think so. 
Probably that is because generally initialization is the only way for hardware/devices
to register a MAC address with the applications/stack.

For dynamic MAC change, the request needs to come from the VF.

2017-01-25 21:13 UTC, stephen-hurd requested changes
Minor changes required.  Looks good otherwise.

2017-01-25 21:13 UTC, stephen-hurd commented on drivers/net/bnxt/bnxt_cpr.c
> +	fwd_cmd = (struct input *)bp->pf.vf_info[fw_vf_id - bp->pf.first_vf_id].req_buf;
Fixes like these should be a separate pull request.

2017-01-25 21:13 UTC, stephen-hurd commented on drivers/net/bnxt/rte_pmd_bnxt.c
> +		RTE_LOG(ERR, PMD, "Attempt to set PF loopback on none-PF port %d!\n",
Should be either "non-PF" or "VF".

2017-01-25 21:13 UTC, stephen-hurd commented on drivers/net/bnxt/rte_pmd_bnxt.c
> +		RTE_LOG(ERR, PMD, "Attempt to set VF %d mac address on none-PF port %d!\n",
As above... non-PF or VF

2017-01-26 02:19 UTC, stephen-hurd approved these changes

2017-01-26 02:27 UTC, merged